services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:14-alpine
    container_name: vts_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vts_db
    ports:
      - "5432:5432"
    restart: always
